FROM	alpine:3.13

WORKDIR /app

RUN		apk add --update nodejs --no-cache --quiet
RUN		apk add --update npm --no-cache --quiet
RUN		apk add --update bash --no-cache --quiet

RUN		npm install --silent
CMD		[ "tail", "-f" ]