FROM 	alpine:3.13

WORKDIR /app

RUN		apk add --update nodejs --no-cache --quiet
RUN		apk add --update npm --no-cache --quiet
RUN		apk add --update bash --no-cache --quiet

COPY	package*.json ./
RUN		npm install --silent

COPY	. .

CMD		[ "tail", "-f" ]