version: '3'

networks:
  net-db:
  net-proxy:

services:
  reverse_proxy:
    container_name: transcendence_reverse_proxy
    build:
      context: ./../reverse_proxy/
    image: transcendence/reverse_proxy
    restart: unless-stopped
    networks:
      - net-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "${APP_PORT}:${APP_PORT}"

  frontend:
    container_name: transcendence_frontend
    build:
      context: ./../frontend/
      dockerfile: ./docker/Dockerfile.dev
    image: transcendence/frontend:latest
    volumes:
      - ./../frontend/:/app
    restart: unless-stopped
    networks:
      - net-proxy

  backend:
    container_name: transcendence_backend
    depends_on:
      - db
    build:
      context: ./../backend/
      dockerfile: ./docker/Dockerfile
    image: transcendence/backend:latest
    networks:
      - net-db
      - net-proxy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SESSION_SECRET=${BACKEND_SESSION_SECRET}
      - INTRA42_UID=${INTRA42_UID}
      - INTRA42_SECRET=${INTRA42_SECRET}
      - INTRA42_CALLBACK_URL=${INTRA42_CALLBACK_URL}
    restart: unless-stopped

  db:
    container_name: transcendence_db
    image: bitnami/postgresql:latest
    networks:
      - net-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRESQL_TIMEZONE=${POSTGRES_TZ}
      - POSTGRESQL_LOG_TIMEZONE=${POSTGRES_TZ}
      - TZ=${POSTGRES_TZ}
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@42.fr
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - net-db
    ports:
      - "5000:80"
    restart: unless-stopped